import type { Metadata } from 'next';
import './globals.css';
import { notoSans, notoSansMono } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSans.variable} ${notoSansMono.variable}`}>
      <body className={`font-[family-name:var(--font-noto-sans)] antialiased`}>
        {children}
      </body>
    </html>
  );
}
